import { Project, Task, Department } from '@/types'

export const ELARA_DEPARTMENTS: Department[] = [
  {
    id: 'dept-sales-crm',
    name: 'Sales & CRM',
    description: 'Leads, follow-ups, site visits, bookings, payment milestones, documentation.',
    team_name: 'Elara Home',
  },
  {
    id: 'dept-construction-design',
    name: 'Construction & Design',
    description: 'Site execution, drawings, consultant decisions, contractor actions, quality and safety issues.',
    team_name: 'Elara Home',
  },
  {
    id: 'dept-approvals-compliance',
    name: 'Approvals & Compliance',
    description: 'TCP/RERA matters, government approvals, licences, statutory submissions and renewals.',
    team_name: 'Elara Home',
  },
  {
    id: 'dept-finance-procurement',
    name: 'Finance & Procurement',
    description: 'Budgets, purchase orders, vendor payments, quotations, billing and cost approvals.',
    team_name: 'Elara Home',
  },
  {
    id: 'dept-marketing-cx',
    name: 'Marketing & Customer Experience',
    description: 'Campaigns, brochures, events, website updates, buyer communication and handover preparation.',
    team_name: 'Elara Home',
  },
  {
    id: 'dept-project-admin',
    name: 'Project Administration',
    description: 'Hiring, manpower, meetings, reporting, travel, office/site requirements and general coordination.',
    team_name: 'Elara Home',
  },
]

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'elara-sales-crm',
    name: 'Elara Home – Sales & CRM Test Project',
    department: 'Sales & CRM',
    team_name: 'Elara Home',
    description: 'Leads, follow-ups, site visits, bookings, payment milestones, documentation.',
    color: '#3b82f6',
    created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: 'elara-construction-design',
    name: 'Elara Home – Construction & Design Test Project',
    department: 'Construction & Design',
    team_name: 'Elara Home',
    description: 'Site execution, drawings, consultant decisions, contractor actions, quality and safety issues.',
    color: '#10b981',
    created_at: new Date(Date.now() - 86400000 * 9).toISOString(),
  },
  {
    id: 'elara-approvals-compliance',
    name: 'Elara Home – Approvals & Compliance Test Project',
    department: 'Approvals & Compliance',
    team_name: 'Elara Home',
    description: 'TCP/RERA matters, government approvals, licences, statutory submissions and renewals.',
    color: '#8b5cf6',
    created_at: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: 'elara-finance-procurement',
    name: 'Elara Home – Finance & Procurement Test Project',
    department: 'Finance & Procurement',
    team_name: 'Elara Home',
    description: 'Budgets, purchase orders, vendor payments, quotations, billing and cost approvals.',
    color: '#f59e0b',
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: 'elara-marketing-cx',
    name: 'Elara Home – Marketing & Customer Experience Test Project',
    department: 'Marketing & Customer Experience',
    team_name: 'Elara Home',
    description: 'Campaigns, brochures, events, website updates, buyer communication and handover preparation.',
    color: '#ec4899',
    created_at: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: 'elara-project-admin',
    name: 'Elara Home – Project Administration Test Project',
    department: 'Project Administration',
    team_name: 'Elara Home',
    description: 'Hiring, manpower, meetings, reporting, travel, office/site requirements and general coordination.',
    color: '#06b6d4',
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
]

export const MOCK_TASKS: Task[] = [
  // 1. Sales & CRM
  {
    id: 'task-sales-1',
    title: 'Add sample lead',
    project_id: 'elara-sales-crm',
    status: 'pending',
    assigned_users: ['Kanav', 'Rachit'],
    progress: 0,
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    due_date: new Date(Date.now() + 86400000 * 4).toISOString(),
    priority: 'medium',
    description: 'Capture inquiry from prospective home buyer for Phase 1.',
  },
  {
    id: 'task-sales-2',
    title: 'Schedule sample site visit',
    project_id: 'elara-sales-crm',
    status: 'in_progress',
    assigned_users: ['Rachit'],
    progress: 50,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    due_date: new Date(Date.now() + 86400000 * 2).toISOString(),
    priority: 'high',
    description: 'Coordinate site tour for registered client this weekend.',
  },
  {
    id: 'task-sales-3',
    title: 'Update sample booking',
    project_id: 'elara-sales-crm',
    status: 'completed',
    assigned_users: ['Kanav'],
    progress: 100,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    due_date: new Date(Date.now() - 86400000 * 1).toISOString(),
    priority: 'low',
    description: 'Milestone payment verified and booking receipt generated.',
  },

  // 2. Construction & Design
  {
    id: 'task-const-1',
    title: 'Review sample drawing',
    project_id: 'elara-construction-design',
    status: 'in_progress',
    assigned_users: ['Rachit', 'Bhirmala'],
    progress: 60,
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    due_date: new Date(Date.now() + 86400000 * 3).toISOString(),
    priority: 'high',
    description: 'Architectural structural drawings review for foundation approval.',
  },
  {
    id: 'task-const-2',
    title: 'Check site execution',
    project_id: 'elara-construction-design',
    status: 'pending',
    assigned_users: ['Rachit'],
    progress: 20,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    due_date: new Date(Date.now() + 86400000 * 5).toISOString(),
    priority: 'medium',
    description: 'Conduct weekly quality audit on foundation pouring.',
  },
  {
    id: 'task-const-3',
    title: 'Resolve sample quality issue',
    project_id: 'elara-construction-design',
    status: 'delay',
    assigned_users: ['Bhirmala'],
    progress: 30,
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    due_date: new Date(Date.now() + 86400000 * 1).toISOString(),
    priority: 'high',
    description: 'Vendor material delivery delayed by 2 days. Expedited shipment requested.',
  },

  // 3. Approvals & Compliance
  {
    id: 'task-appr-1',
    title: 'Review sample approval',
    project_id: 'elara-approvals-compliance',
    status: 'pending',
    assigned_users: ['Kanav'],
    progress: 0,
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    due_date: new Date(Date.now() + 86400000 * 6).toISOString(),
    priority: 'medium',
    description: 'Check municipal water and power sanction compliance.',
  },
  {
    id: 'task-appr-2',
    title: 'Prepare sample submission',
    project_id: 'elara-approvals-compliance',
    status: 'in_progress',
    assigned_users: ['Bhirmala'],
    progress: 40,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    due_date: new Date(Date.now() + 86400000 * 2).toISOString(),
    priority: 'high',
    description: 'Compile TCP/RERA statutory compliance documentation dossier.',
  },
  {
    id: 'task-appr-3',
    title: 'Track sample compliance item',
    project_id: 'elara-approvals-compliance',
    status: 'completed',
    assigned_users: ['Kanav', 'Bhirmala'],
    progress: 100,
    created_at: new Date(Date.now() - 86400000 * 6).toISOString(),
    due_date: new Date(Date.now() - 86400000 * 1).toISOString(),
    priority: 'low',
    description: 'Fire safety certificate renewed and filed with regulatory authority.',
  },

  // 4. Finance & Procurement
  {
    id: 'task-fin-1',
    title: 'Review sample quotation',
    project_id: 'elara-finance-procurement',
    status: 'in_progress',
    assigned_users: ['Bhagwan Dass'],
    progress: 75,
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    due_date: new Date(Date.now() + 86400000 * 2).toISOString(),
    priority: 'medium',
    description: 'Evaluate competitive quotes for structural steel procurement.',
  },
  {
    id: 'task-fin-2',
    title: 'Create sample purchase order',
    project_id: 'elara-finance-procurement',
    status: 'pending',
    assigned_users: ['Bhagwan Dass'],
    progress: 0,
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    due_date: new Date(Date.now() + 86400000 * 3).toISOString(),
    priority: 'high',
    description: 'Issue PO #GEI-2026-088 for electrical conduits and cabling.',
  },
  {
    id: 'task-fin-3',
    title: 'Verify sample vendor payment',
    project_id: 'elara-finance-procurement',
    status: 'completed',
    assigned_users: ['Bhagwan Dass'],
    progress: 100,
    created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
    due_date: new Date(Date.now() - 86400000 * 2).toISOString(),
    priority: 'low',
    description: 'Vendor invoice audited and payment release cleared by accounts.',
  },

  // 5. Marketing & Customer Experience
  {
    id: 'task-mkt-1',
    title: 'Prepare sample campaign',
    project_id: 'elara-marketing-cx',
    status: 'pending',
    assigned_users: ['Rachit'],
    progress: 10,
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    due_date: new Date(Date.now() + 86400000 * 5).toISOString(),
    priority: 'medium',
    description: 'Plan festive promotional launch campaign for Phase 2 villas.',
  },
  {
    id: 'task-mkt-2',
    title: 'Update sample brochure',
    project_id: 'elara-marketing-cx',
    status: 'in_progress',
    assigned_users: ['Bhagwan Dass'],
    progress: 50,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    due_date: new Date(Date.now() + 86400000 * 3).toISOString(),
    priority: 'low',
    description: 'Refresh villa floorplans, 3D renderings, and specifications list.',
  },
  {
    id: 'task-mkt-3',
    title: 'Prepare sample buyer communication',
    project_id: 'elara-marketing-cx',
    status: 'completed',
    assigned_users: ['Rachit', 'Bhagwan Dass'],
    progress: 100,
    created_at: new Date(Date.now() - 86400000 * 6).toISOString(),
    due_date: new Date(Date.now() - 86400000 * 1).toISOString(),
    priority: 'high',
    description: 'Quarterly construction progress newsletter dispatched to buyers.',
  },

  // 6. Project Administration
  {
    id: 'task-adm-1',
    title: 'Schedule sample meeting',
    project_id: 'elara-project-admin',
    status: 'pending',
    assigned_users: ['Developer'],
    progress: 0,
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    due_date: new Date(Date.now() + 86400000 * 1).toISOString(),
    priority: 'medium',
    description: 'Coordinate bi-weekly cross-departmental alignment sync.',
  },
  {
    id: 'task-adm-2',
    title: 'Prepare sample report',
    project_id: 'elara-project-admin',
    status: 'in_progress',
    assigned_users: ['Kanav', 'Developer'],
    progress: 65,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    due_date: new Date(Date.now() + 86400000 * 2).toISOString(),
    priority: 'high',
    description: 'Consolidate monthly milestone progress and budget variance overview.',
  },
  {
    id: 'task-adm-3',
    title: 'Coordinate sample manpower requirement',
    project_id: 'elara-project-admin',
    status: 'blocker',
    assigned_users: ['Developer'],
    progress: 20,
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    due_date: new Date(Date.now() + 86400000 * 1).toISOString(),
    priority: 'high',
    is_blocked: true,
    blocker_reason: 'Awaiting site contractor labor mobilization clearance.',
    blockers_count: 1,
    description: 'Staffing for site surveying and soil testing team awaiting clearance.',
  },
]
